version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      - churn_app

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  churn_app:
    image: avivsimontahar/churn-pro:latest
    container_name: churn_app
    ports:
      - "8080:8080"
    networks:
      - monitoring
    environment:
      - APP_ENV=production
    depends_on:
      - prometheus

volumes:
  grafana-data:
  prometheus-data:

networks:
  monitoring:
    driver: bridge