server:
  host: "0.0.0.0"                             # The IP the fast api will listen on
  port: 8080                             
  reload: true                                # Enable auto-reload for development, disable for production

model:
  model_path: "models/churn_model.pickle"   
  output_dir: "outputs/"                      # Directory for storing output files

